#!/usr/bin/env python3
"""Build catalog-en.md / catalog-en.csv from the Chinese catalog."""
from __future__ import annotations

import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent

PREFIX = {
    "國宴大師": "State Banquet Master",
    "国宴大师": "State Banquet Master",
    "大師小灶": "Master's small stove",
    "老飯骨學堂": "LaoFanGu Classroom",
    "老飯骨家宴": "LaoFanGu family banquet",
    "老饭骨家宴": "LaoFanGu family banquet",
    "老飯骨潮州行": "LaoFanGu in Chaozhou",
    "老飯骨": "LaoFanGu",
}

# Dish names as they appear after the • (or inside 【】).
DISH = {
    "XO醬爆龍鳳球": "XO sauce dragon-phoenix balls",
    "一品燒餅": "Yipin sesame flatbread",
    "一小時一桌飯": "A full table in one hour",
    "丁香酥鴨": "Clove crispy duck",
    "三不沾": "Sanbuzhan (sweet egg custard)",
    "三元牛衝": "Sanyuan beef tripe",
    "三叔家饺子": "Third Uncle's family dumplings",
    "三文魚刺身": "Salmon sashimi",
    "三杯雞": "Three-cup chicken",
    "三椒羊排": "Three-pepper lamb chops",
    "三汁燜鍋": "Three-sauce claypot",
    "三瓜燉排骨": "Three-melon pork rib stew",
    "三絲扣干貝": "Three-shred scallop mold",
    "三色彩蛋": "Three-color steamed eggs",
    "三鮮餃子": "Three-delicacy dumplings",
    "上湯焗龍蝦": "Superior-stock baked lobster",
    "中式牛柳": "Chinese-style beef tenderloin",
    "中式豉椒羊排": "Black-bean chili lamb chops",
    "中式面果": "Chinese fried dough twists",
    "中秋月饼": "Mid-Autumn mooncakes",
    "九轉大腸": "Nine-turn large intestine",
    "九轉帶魚": "Nine-turn hairtail",
    "乾燴大蝦": "Dry-braised prawns",
    "乾炒河粉": "Dry-fried rice noodles",
    "乾炒牛河": "Dry-fried beef hor fun",
    "乾炸裡脊": "Dry-fried pork tenderloin",
    "乾炸里脊": "Dry-fried pork tenderloin",
    "乾煸牛肉絲": "Dry-fried shredded beef",
    "乾煸豆角": "Dry-fried green beans",
    "乾燒冬筍": "Dry-braised winter bamboo",
    "乾鍋肥腸": "Dry-pot pork intestine",
    "乾隆白菜": "Qianlong cabbage",
    "二伯炸醬面": "Er Bo's zhajiangmian",
    "二伯炸雞": "Er Bo's fried chicken",
    "二伯红烧肉": "Er Bo's red-braised pork",
    "二伯醉蟹": "Er Bo's drunken crab",
    "五仁月餅": "Five-nut mooncakes",
    "五色餃子": "Five-color dumplings",
    "五香燜全鴿": "Five-spice whole pigeon",
    "京酱肉丝": "Beijing shredded pork (jing jiang rou si)",
    "京醬肉絲": "Beijing shredded pork (jing jiang rou si)",
    "人參老雞湯": "Ginseng old-hen soup",
    "什錦炒飯": "Deluxe fried rice",
    "作業點評": "Homework critique",
    "侉燉魚": "Kua-style stewed fish",
    "侯爺醉蟹": "Master Hou's drunken crab",
    "內蒙奶茶": "Inner Mongolian milk tea",
    "內蒙燒賣": "Inner Mongolian siu mai",
    "全家福": "Happy Family (assorted banquet stir-fry)",
    "兩吃蝦": "Prawns two ways",
    "八寶葫蘆鴨": "Eight-treasure gourd duck",
    "八寶飯": "Eight-treasure rice",
    "八寶鴿子": "Eight-treasure pigeon",
    "八爪魚紅燒肉": "Octopus red-braised pork",
    "六必居炒醬瓜": "Liubiju stir-fried pickled melon",
    "冬瓜蓉": "Winter melon mash",
    "冬筍魷魚里脊絲": "Winter bamboo, squid, and shredded tenderloin",
    "冬菇扒茄子": "Braised eggplant with shiitake",
    "冬陰功湯": "Tom yum soup",
    "冰水蝦片": "Ice-water prawn crackers",
    "冰糖肘子": "Rock-sugar pork hock",
    "冰糖葫蘆": "Candied hawthorn (tanghulu)",
    "刀削麵": "Knife-cut noodles",
    "刀工/切絲": "Knife skill / julienne",
    "切肉絲/炒肉絲": "Shredding and stir-frying pork",
    "刺猬丸子": "Hedgehog meatballs",
    "剁椒魚": "Chopped-chili fish",
    "剁椒鱼头": "Chopped-chili fish head",
    "勞動節特輯": "Labor Day special",
    "包粽子": "How to wrap zongzi",
    "匈牙利燴牛肉": "Hungarian beef stew",
    "十八秒爆炒吊龍": "18-second stir-fried pork jowl",
    "千層肉餅": "Thousand-layer meat pie",
    "千島脆白玉": "Thousand-island crispy tofu",
    "南煎丸子": "Southern pan-fried meatballs",
    "卤煮火烧": "Beijing lu zhu huo shao",
    "印尼炒饭": "Indonesian fried rice",
    "原漿豆腐": "Fresh-set tofu",
    "去骨香酥鸭": "Boneless crispy duck",
    "去魚骨&片魚肉": "Deboning and slicing fish",
    "參黃養生湯": "Ginseng-and-turmeric tonic soup",
    "叉燒肉": "Char siu pork",
    "发财鸭": "Prosperity duck",
    "口蘑鸡块": "Chicken with button mushrooms",
    "合味雞翅": "Hewei chicken wings",
    "合川肉片": "Hechuan sliced pork",
    "吉慶有魚": "Auspicious fish",
    "吉祥燈籠蝦": "Lucky lantern prawns",
    "吊汤": "Stock-making (diao tang)",
    "味汆儿面": "Wei-cuan noodles",
    "咖哩羊肉": "Curry lamb",
    "咖哩蟹": "Curry crab",
    "咖哩雞飯": "Curry chicken rice",
    "咖啡牛柳": "Coffee beef tenderloin",
    "咖喱虾": "Curry shrimp",
    "唐山花椒肉": "Tangshan Sichuan-peppercorn pork",
    "啫啫三文魚頭": "Sizzling salmon head (je je)",
    "啫啫雞煲": "Sizzling chicken claypot",
    "喜慶蝦球": "Festive shrimp balls",
    "四喜丸子": "Four-joy meatballs",
    "四川香碗": "Sichuan fragrant bowl",
    "回鍋肉": "Twice-cooked pork",
    "回锅肉": "Twice-cooked pork",
    "国宴核桃酪": "State-banquet walnut cream",
    "國宴大師•": "State Banquet Master",
    "國宴干燒魚": "State-banquet dry-braised fish",
    "國宴東坡肉": "State-banquet Dongpo pork",
    "國宴羊肉抓飯": "State-banquet lamb pilaf",
    "國宴蟹黃魚丸": "State-banquet crab-roe fish balls",
    "國宴雞豆花": "State-banquet chicken tofu pudding",
    "圓夢燒餅": "Dream-fulfilling shaobing",
    "圓白菜炒粉條": "Stir-fried cabbage with glass noodles",
    "土豆炖牛肉": "Potato beef stew",
    "土豆燉牛肉": "Potato beef stew",
    "土豆球": "Potato balls",
    "地三鮮": "Di san xian (potato, eggplant, pepper)",
    "塌肉片": "Pan-collapsed pork slices",
    "塌鍋飯": "Claypot collapsed rice",
    "壽喜燒": "Sukiyaki",
    "夏日風情": "Summer flavors",
    "大千干烧鱼": "Zhang Daqian dry-braised fish",
    "大媽白菜": "Auntie's cabbage",
    "大烩菜": "Big mixed stew",
    "大煮乾絲": "Yangzhou dry tofu shreds in broth",
    "大煮干絲": "Yangzhou dry tofu shreds in broth",
    "大爷咕咾虾球": "Grandpa's sweet-and-sour shrimp balls",
    "大爺涼面": "Grandpa's cold noodles",
    "大爺炸醬麵": "Grandpa's zhajiangmian",
    "大盘鸡": "Dapanji (big-plate chicken)",
    "大盤雞": "Dapanji (big-plate chicken)",
    "大肉方": "Big square of braised pork",
    "大蒜炝牛舌": "Garlic-flash beef tongue",
    "大蝦燒白菜": "Prawns with napa cabbage",
    "大酥肉": "Big crispy fried pork",
    "太后养生鸭": "Empress Dowager tonic duck",
    "太陽餅": "Sun cakes (taiyang bing)",
    "奶汁海鮮方便麵": "Creamy seafood instant noodles",
    "奶油南瓜素燴": "Creamy pumpkin vegetable stew",
    "奶油炸糕": "Cream fried cakes",
    "奶油烤雜拌": "Cream-baked mixed grill",
    "奶油蘑菇湯": "Cream of mushroom soup",
    "好好吃飯": "Eat well",
    "姜爆里脊絲": "Ginger-fried shredded tenderloin",
    "孜然羊肉": "Cumin lamb",
    "它似蜜": "Ta si mi (sweet-fried lamb)",
    "宋嫂魚羹方便麵": "Sister Song fish soup instant noodles",
    "宫保鸡丁": "Kung pao chicken",
    "宫廷榛子酱": "Palace hazelnut sauce",
    "宮保牛肋": "Kung pao beef ribs",
    "宮保蝦球": "Kung pao shrimp balls",
    "宮保雞丁": "Kung pao chicken",
    "宮廷佛手捲": "Palace Buddha's-hand rolls",
    "宮廷小窩頭": "Palace mini corn buns",
    "宮廷烤肉": "Palace roast meat",
    "宮廷紅燒肉": "Palace red-braised pork",
    "宮廷醬牛肉": "Palace sauced beef",
    "宮廷黃瓜醬": "Palace cucumber sauce",
    "家常海參": "Home-style sea cucumber",
    "家常烤肉": "Home-style roast meat",
    "家常肉餅小米粥": "Home-style meat pie and millet porridge",
    "家常豆腐": "Home-style tofu",
    "家常黃酒燉雞": "Home-style huangjiu chicken stew",
    "家庭大肉餅": "Family meat pie",
    "家燒帶魚": "Home-braised hairtail",
    "家鄉小河魚": "Hometown small river fish",
    "家鄉豆腐": "Hometown tofu",
    "富察皇后糕": "Empress Fucha cakes",
    "富貴盆菜": "Prosperity basin feast",
    "富貴蝦包": "Prosperity shrimp parcels",
    "寶島滷肉飯": "Taiwanese lu rou fan",
    "寶石蝦球&豆瓣魚": "Jewel shrimp balls & douban fish",
    "將軍排骨": "General's spare ribs",
    "小小獅子頭": "Mini lion's-head meatballs",
    "小棗粽子": "Jujube zongzi",
    "小炒牛肉": "Quick-fried beef",
    "小炒肉": "Hunan quick-fried pork",
    "小炒茄丁": "Quick-fried diced eggplant",
    "小炒黃牛肉": "Quick-fried yellow beef",
    "小籠牛肉": "Xiaolong beef",
    "小豆沫": "Mung-bean mash",
    "小院豆腐": "Courtyard tofu",
    "尚酥令": "Shang su ling pastry",
    "層酥燒餅": "Layered flaky shaobing",
    "山東海參": "Shandong sea cucumber",
    "山東炒雞": "Shandong stir-fried chicken",
    "山東炒雞燜面": "Shandong chicken with braised noodles",
    "山東燒雞": "Shandong roast chicken",
    "山東獅子頭": "Shandong lion's-head meatballs",
    "山西糖火燒": "Shanxi sweet huoshao",
    "左宗棠雞": "General Tso's chicken",
    "干炒牛河": "Dry-fried beef hor fun",
    "干炸丸子": "Dry-fried meatballs",
    "干鍋花菜": "Dry-pot cauliflower",
    "平橋豆腐": "Pingqiao tofu",
    "年夜飯": "New Year's Eve dinner",
    "年糕": "Nian gao (New Year rice cake)",
    "开水白菜": "Boiled-water cabbage",
    "得莫利燉魚": "Demoli stewed fish",
    "德國啤酒烤豬肘": "German beer-roasted pork knuckle",
    "德州扒雞": "Dezhou braised chicken",
    "心裡美汆丸子": "Watermelon-radish dropped meatballs",
    "快樂肘子": "Happy pork hock",
    "惠靈頓月餅": "Wellington mooncakes",
    "惠靈頓牛排": "Beef Wellington",
    "意大利面": "Pasta",
    "意大利黑醋牛肋排": "Italian balsamic beef short ribs",
    "意式千層面": "Lasagna",
    "愛爾蘭清湯羊肉": "Irish clear lamb broth",
    "成都雞": "Chengdu chicken",
    "戴安娜牛排": "Steak Diane",
    "扁豆燜面": "Green-bean braised noodles",
    "手抓羊肉": "Hand-pulled lamb",
    "手抓飯": "Hand-eaten pilaf (zhua fan)",
    "手抓餅": "Hand-grabbed pancake",
    "手抓饭": "Hand-eaten pilaf (zhua fan)",
    "手搓冰粉": "Hand-rubbed ice jelly",
    "扒白菜卷": "Braised cabbage rolls",
    "扒肉條": "Braised pork strips",
    "打滷面": "Noodles in thickened gravy",
    "抓炒腰花": "Toss-fried kidney flowers",
    "抓炒蝦仁": "Toss-fried shrimp",
    "抓炒里脊": "Toss-fried tenderloin",
    "抓炒魚片": "Toss-fried fish slices",
    "拆燴魚頭": "Braised picked fish head",
    "拌三文魚": "Mixed salmon",
    "拔絲紅薯": "Candied pulled sweet potato",
    "排骨燉豆角": "Spare ribs stewed with beans",
    "揚州炒飯": "Yangzhou fried rice",
    "摔蘿蔔燉羊排": "Slapped-radish lamb chop stew",
    "撈汁小海鮮": "Dressed cold seafood",
    "擔擔麵": "Dan dan noodles",
    "文思豆腐": "Wensi tofu",
    "新疆抓飯": "Xinjiang pilaf",
    "春天開心湯": "Spring happy soup",
    "春肘": "Spring pork hock",
    "春餅": "Spring pancakes",
    "會跳舞的板栗燒雞": "Dancing chestnut roast chicken",
    "朝鮮冷面": "Korean cold noodles",
    "朝鮮泡菜": "Korean kimchi",
    "木須肉": "Moo shu pork",
    "木须肉": "Moo shu pork",
    "杏乾燒蹄筋": "Dried-apricot braised tendon",
    "杏醬": "Apricot sauce",
    "杏香虾球": "Apricot shrimp balls",
    "東北小燒烤": "Northeastern small barbecue",
    "東北飯包": "Northeastern rice wraps",
    "東坡牛肉": "Dongpo beef",
    "東坡肉": "Dongpo pork",
    "東坡豆腐": "Dongpo tofu",
    "東坡豆花": "Dongpo tofu pudding",
    "東安仔雞": "Dong'an young chicken",
    "松子肉": "Pine-nut pork",
    "松露鹽牛排": "Truffle-salt steak",
    "松鼠桂魚": "Squirrel-shaped mandarin fish",
    "果味魚": "Fruit-flavored fish",
    "果汁蝦球": "Fruit-juice shrimp balls",
    "柴把鴨子": "Faggot-tied duck",
    "栗子扒白菜": "Chestnut braised cabbage",
    "栗子燒排骨": "Chestnut spare ribs",
    "栗子燒雞": "Chestnut roast chicken",
    "栗子糕": "Chestnut cake",
    "栗子翅中": "Chestnut mid-wings",
    "桂花水汆羊肉": "Osmanthus dropped lamb",
    "桃仁酥鴨方": "Walnut crispy duck squares",
    "桃仁雞丁": "Walnut diced chicken",
    "桃膠煮艿芋": "Peach-gum taro",
    "桃花泛": "Peach-blossom rice",
    "梅干菜糖包": "Mei gan cai sweet buns",
    "梅花四素": "Plum-blossom four vegetables",
    "梅菜扣肉": "Mei cai kou rou (pork with preserved mustard)",
    "棋子豬蹄": "Chess-piece pig trotters",
    "椒鹽蝦": "Salt-and-pepper shrimp",
    "椒鹽豬排": "Salt-and-pepper pork chops",
    "椒麻雞": "Numbing-pepper chicken",
    "楊枝甘露": "Mango pomelo sago",
    "榨菜肉絲": "Shredded pork with zha cai",
    "榴蓮酥": "Durian pastry",
    "樟茶芝麻鴨排": "Camphor-tea sesame duck chops",
    "櫻桃肉": "Cherry pork",
    "櫻花蝦油飯": "Sakura-shrimp oil rice",
    "欖菜肉丁長壽果": "Olive-vegetable diced pork with peanuts",
    "毛氏紅燒肉": "Mao-style red-braised pork",
    "毛蚶子燜米飯": "Blood-clam claypot rice",
    "毛血旺": "Mao xue wang (Sichuan blood stew)",
    "水晶蔬菜包": "Crystal vegetable buns",
    "水晶蘿蔔丸": "Crystal radish balls",
    "水汆丸子": "Dropped meatballs in water",
    "水炒香椿蝦": "Water-fried toon shrimp",
    "水煎包": "Pan-fried buns (shui jian bao)",
    "水煮牛肉": "Boiled beef in chili broth",
    "水煮肉片": "Boiled pork slices in chili broth",
    "汆水蛋": "Dropped eggs in broth",
    "汆白肉漬菜粉": "Dropped pork with pickled greens and noodles",
    "汗蒸鱼": "Sweat-steamed fish",
    "江團燉豆腐": "Jiangtuan fish stewed with tofu",
    "江米涼果": "Glutinous-rice cold sweets",
    "沙琪瑪": "Sachima",
    "沙茶陳皮燒牛肋": "Shacha tangerine-peel beef ribs",
    "沙薑豬手": "Sand ginger pig trotters",
    "河間包肉": "Hejian wrapped pork",
    "油封鴨": "Duck confit",
    "油泼猪手": "Oil-splashed pig trotters",
    "油潑面": "Oil-splashed noodles",
    "油炸冰激凌": "Deep-fried ice cream",
    "油焖大虾": "Oil-braised prawns",
    "油燜大蝦": "Oil-braised prawns",
    "油爆羅氏蝦": "Flash-fried giant freshwater prawns",
    "法式扒牛排": "French pan-seared steak",
    "法式洋蔥湯": "French onion soup",
    "法式焗蝸牛": "Escargot",
    "法式芝士焗土豆": "French cheese-baked potatoes",
    "法式香煎雞": "French pan-seared chicken",
    "泡椒勁爽三絕": "Pickled-chili three bites",
    "泡菜鱸魚": "Kimchi sea bass",
    "泰式蝦餅": "Thai shrimp cakes",
    "泰式青木瓜沙拉": "Thai green papaya salad",
    "海皇豆腐煲": "Seafood emperor tofu pot",
    "海腸撈飯": "Sea intestine over rice",
    "涮羊肉小料": "Hot-pot lamb dipping sauces",
    "涼拌羊肉": "Cold dressed lamb",
    "涼拌萵筍": "Cold dressed celtuce",
    "涼拌雞蛋羹": "Cold steamed egg",
    "涼拌鯽魚": "Cold dressed crucian carp",
    "涼粉": "Liangfen (mung-bean jelly)",
    "淮山四寶": "Huai shan four treasures",
    "清炸里脊": "Plain deep-fried tenderloin",
    "清燉小酥肉": "Clear-stewed crispy pork",
    "清燉牛肉": "Clear beef stew",
    "清燉獅子頭": "Clear-broth lion's-head meatballs",
    "清燉番茄牛肉": "Clear tomato beef stew",
    "清真醬牛肉": "Halal sauced beef",
    "清蒸桂魚": "Steamed mandarin fish",
    "清蒸武昌鱼": "Steamed Wuchang bream",
    "港式燒雞": "Hong Kong-style roast chicken",
    "溜肉段": "Northeast fried pork in sauce",
    "滑溜肉片": "Velveted pork slices",
    "滑溜里脊": "Velveted tenderloin",
    "滑溜里脊加荸薺": "Velveted tenderloin with water chestnuts",
    "滑蛋牛肉": "Beef with scrambled egg",
    "滑蛋蝦仁": "Shrimp with scrambled egg",
    "火焰醉龙虾": "Flaming drunken lobster",
    "火焰鹽焗雞": "Flaming salt-baked chicken",
    "火燎鴨心": "Flame-seared duck hearts",
    "火腿腸": "Ham sausage",
    "炒五花肉": "Stir-fried pork belly",
    "炒土豆丝": "Stir-fried shredded potato",
    "炒方便麵": "Stir-fried instant noodles",
    "炒牛肉丝": "Stir-fried shredded beef",
    "炒疙瘩": "Stir-fried dough knots",
    "炒紅果": "Stir-fried hawthorn",
    "炒紅燒肉": "Stir-fried leftover red-braised pork",
    "炒肉片": "Stir-fried pork slices",
    "炒肝": "Beijing chaogan",
    "炒豆渣": "Stir-fried okara",
    "炒面茶": "Stir-fried millet tea",
    "炒鹹菜絲": "Stir-fried pickled-vegetable shreds",
    "炒麻豆腐": "Stir-fried ma doufu",
    "炙子炒麵": "Griddle-fried noodles",
    "炙子烤肉": "Griddle barbecue",
    "炮仗雞捲": "Firecracker chicken rolls",
    "炸三角": "Fried triangles",
    "炸小黃魚": "Fried small yellow croaker",
    "炸年糕": "Fried nian gao",
    "炸扁丸子": "Fried flat meatballs",
    "炸排叉": "Fried paicha",
    "炸松肉": "Fried puffy pork",
    "炸油条": "Youtiao",
    "炸油餅": "Fried oil cakes",
    "炸溜鸡丁": "Fried then sauced diced chicken",
    "炸牛肉丸子": "Fried beef meatballs",
    "炸素丸子": "Fried vegetarian balls",
    "炸藕盒": "Fried lotus-root sandwiches",
    "炸豬排": "Fried pork cutlet",
    "炸醬面": "Zhajiangmian",
    "炸醬麵": "Zhajiangmian",
    "炸雞": "Fried chicken",
    "炸雞皮": "Fried chicken skin",
    "炸雞腿": "Fried chicken drumsticks",
    "炸雪糕": "Fried ice cream",
    "烏雞咸蛋捲": "Black-chicken salted-egg rolls",
    "烏魚蛋湯": "Cuttlefish-egg soup",
    "烙餅攤雞蛋": "Griddled pancake with egg",
    "烤五花肉": "Roast pork belly",
    "烤羊排": "Roast lamb chops",
    "烤肋排": "Roast ribs",
    "烤腦花": "Grilled brain",
    "烤腰子": "Grilled kidneys",
    "烤雞翅": "Roast chicken wings",
    "烤鸡翅": "Roast chicken wings",
    "無花果浸土雞": "Fig-infused free-range chicken",
    "無錫排骨&果子乾": "Wuxi ribs & dried fruit",
    "焦溜丸子": "Crisp-fried meatballs in sauce",
    "焦溜肉片": "Crisp-fried pork slices in sauce",
    "焦炒方便麵": "Scorched stir-fried instant noodles",
    "煎三文魚": "Pan-fried salmon",
    "煎烹大蝦": "Pan-fried then tossed prawns",
    "煎烹牛里脊": "Pan-fried then tossed beef tenderloin",
    "煎烹雞肉串": "Pan-fried then tossed chicken skewers",
    "煎釀鮮蘑": "Pan-fried stuffed mushrooms",
    "煙台炒麵": "Yantai fried noodles",
    "照燒雞": "Teriyaki chicken",
    "煨牛肉": "Slow-braised beef",
    "煨臍門": "Slow-braised pork navel",
    "煲仔饭": "Claypot rice",
    "熏豬頭": "Smoked pig's head",
    "熏醬豬蹄": "Smoked-and-sauced trotters",
    "熏鱼": "Smoked fish",
    "熗炒蓮花白": "Flash-fried cabbage",
    "熗鍋面": "Hot-oil noodles",
    "熘肝尖": "Sauced liver tips",
    "熘魚脯": "Sauced fish maw",
    "熬炸醬": "Slow-fried zhajiang sauce",
    "燒二冬": "Braised two winters (bamboo and mushroom)",
    "燒排骨酥": "Braised spare-rib crisps",
    "燒椒皮蛋": "Burnt-chili century egg",
    "燒椒豬手": "Burnt-chili pig trotters",
    "燒汁牛肉粒": "Glazed beef cubes",
    "燒燴爪尖": "Braised trotter tips",
    "燒羊肉": "Braised lamb",
    "燒茄子": "Braised eggplant",
    "燙飯": "Scalded rice",
    "爆三樣": "Flash-fried three meats",
    "爆兩樣": "Flash-fried two meats",
    "爆肚": "Flash-fried tripe",
    "爆肚十三吃": "Tripe thirteen ways",
    "爛肉麵": "Minced-pork noodles",
    "牛油果冰淇凌": "Avocado ice cream",
    "牛油果軟煎魚": "Soft-fried fish with avocado",
    "牛油果香煎銀鱈魚": "Pan-seared Chilean sea bass with avocado",
    "牛肉清湯": "Clear beef broth",
    "牛肉漢堡": "Beef burger",
    "牛肉炸醬麵": "Beef zhajiangmian",
    "牛肉煎粉條": "Pan-fried beef with glass noodles",
    "牛肉醬": "Beef sauce",
    "牛肉鍋貼": "Beef potstickers",
    "牛舌餅": "Ox-tongue pastry",
    "狀元雞肉串": "Zhuangyuan chicken skewers",
    "猛火豬肝": "High-heat pork liver",
    "玉簪蝦球": "Jade-hairpin shrimp balls",
    "玉簪雞翼球": "Jade-hairpin chicken-wing balls",
    "玉蘭花": "Magnolia flowers",
    "玫瑰煎餃": "Rose pan-fried dumplings",
    "珊瑚白菜": "Coral cabbage",
    "珍珠豬排": "Pearl pork chops",
    "甜燒白": "Sweet steamed pork with rice",
    "番茄牛肉": "Tomato beef",
    "番茄蝦仁湯": "Tomato shrimp soup",
    "疙瘩汤": "Dough-drop soup",
    "疙瘩湯": "Dough-drop soup",
    "發海參": "Rehydrating sea cucumber",
    "白切雞": "White-cut chicken",
    "白朮豬肚粥": "Atractylodes pork-stomach congee",
    "白湯羊蠍子": "White-broth lamb spine",
    "白湯雜碎": "White-broth offal",
    "白菜雲吞方便麵": "Cabbage wonton instant noodles",
    "百花蒸瓤豆腐": "Baihua stuffed steamed tofu",
    "百花釀帶子": "Baihua stuffed scallops",
    "盆儿里碰": "Pen'er li peng",
    "盆菜": "Poon choi",
    "眉丸海參": "Eyebrow meatball sea cucumber",
    "石鍋豆腐": "Stone-pot tofu",
    "砂鍋羊頭": "Casserole lamb head",
    "砂锅焗虾": "Sand-pot baked shrimp",
    "硬核教學": "Hardcore lesson",
    "碎米雞丁": "Cracked-rice diced chicken",
    "私房土豆絲": "Private-kitchen shredded potato",
    "私房牛肉麵": "Private-kitchen beef noodles",
    "私房羊肉": "Private-kitchen lamb",
    "私房茄子": "Private-kitchen eggplant",
    "秋梨膏": "Autumn pear syrup",
    "秘制燒魚": "Secret roast fish",
    "秘製大魚頭": "Secret big fish head",
    "空心琉璃丸子": "Hollow glazed meatballs",
    "空心饅頭": "Hollow steamed buns",
    "第一集": "Episode 1",
    "第二集": "Episode 2",
    "第四集": "Episode 4",
    "筋頭巴腦": "Tendon-and-cartilage beef",
    "米湯浸時蔬": "Rice-water blanched greens",
    "米粉肉": "Steamed pork with rice meal",
    "粉彩包子": "Pastel baozi",
    "粉絲會員福利": "Members perk",
    "粉蒸肉": "Steamed pork with rice flour",
    "粉蒸豆角": "Steamed beans with rice flour",
    "粽葉雞": "Zongzi-leaf chicken",
    "糊塌子": "Hutazi (griddled mung-bean cakes)",
    "糖卷果": "Candied rolled fruit",
    "糖油餅": "Sugar-oil cakes",
    "糖火燒": "Sweet huoshao",
    "糖醋排骨": "Sweet-and-sour spare ribs",
    "糖醋話梅小排": "Sweet-and-sour plum spare ribs",
    "糖醋里脊": "Sweet-and-sour tenderloin",
    "糖醋魚": "Sweet-and-sour fish",
    "糖醋魚條": "Sweet-and-sour fish strips",
    "糖醋黃花魚": "Sweet-and-sour yellow croaker",
    "糟溜鱼片": "Wine-lees fish slices",
    "紀念袁隆平院士": "In memory of Yuan Longping",
    "紅棗煨肘子": "Jujube slow-braised pork hock",
    "紅樓茄鯗": "Dream of Red Chamber dried eggplant",
    "紅燒大蘿蔔": "Red-braised daikon",
    "紅燒大魚頭": "Red-braised big fish head",
    "紅燒排骨": "Red-braised spare ribs",
    "紅燒牛尾": "Red-braised oxtail",
    "紅燒牛肉": "Red-braised beef",
    "紅燒牛肉麵": "Red-braised beef noodles",
    "紅燒肉": "Red-braised pork",
    "紅燒肉大戰": "Red-braised pork showdown",
    "紅燒裙邊": "Red-braised turtle skirt",
    "紅燒豬蹄": "Red-braised pig trotters",
    "紅燒馬鞍橋": "Red-braised saddle-bridge (pork)",
    "紅燒魷魚片": "Red-braised squid slices",
    "紅燒鰨目魚": "Red-braised sole",
    "紅燜羊肉": "Red-smothered lamb",
    "紅菜湯": "Borscht",
    "紅酒燉牛肋": "Red-wine beef rib stew",
    "紅酒燴牛尾": "Red-wine oxtail",
    "紅酒燴牛肉": "Red-wine beef",
    "紅酒雞": "Red-wine chicken",
    "紙皮素包子": "Paper-skin vegetarian bao",
    "素回鍋肉": "Vegetarian twice-cooked pork",
    "素熗鍋面": "Vegetarian hot-oil noodles",
    "素牛排": "Vegetarian steak",
    "素獅子頭": "Vegetarian lion's-head meatballs",
    "素羊肉串": "Vegetarian lamb skewers",
    "素鱔絲": "Vegetarian shredded eel",
    "紫龍脫袍": "Purple dragon sheds its robe",
    "綠豆竹葉粥": "Mung-bean bamboo-leaf congee",
    "红烧狮子头": "Red-braised lion's-head meatballs",
    "红烧肉": "Red-braised pork",
    "红烧鲤鱼": "Red-braised carp",
    "罐燜牛肉": "Pot-smothered beef",
    "羅漢大蝦": "Luohan prawns",
    "羊棒骨": "Lamb marrow bones",
    "羊肉串": "Lamb skewers",
    "羊肉汆丸子": "Dropped lamb meatballs",
    "羊肉汆面": "Dropped-lamb noodles",
    "羊肉餃子": "Lamb dumplings",
    "羊蝎子": "Lamb spine hot pot",
    "群英薈萃": "Gathering of heroes (radish trio)",
    "羽衣甘藍": "Kale",
    "羽衣甘藍天婦羅": "Kale tempura",
    "羽衣甘藍沙拉": "Kale salad",
    "翡翠羹": "Jade broth",
    "翡翠虾球": "Jade shrimp balls",
    "老佛爺豬手": "Old Buddha pig trotters",
    "老北京灌腸": "Old Beijing guanchang",
    "老北京炒合菜": "Old Beijing stir-fried mixed vegetables",
    "老北京炒酱瓜": "Old Beijing stir-fried sauced melon",
    "老北京炸酱面": "Old Beijing zhajiangmian",
    "老奶奶炒白菜": "Granny's stir-fried cabbage",
    "老媽熏魚": "Mom's smoked fish",
    "老媽蹄花": "Mom's trotter flowers",
    "老廚白菜": "Old-cook cabbage",
    "老式宫保鸡丁": "Old-style kung pao chicken",
    "老式豌豆黃": "Old-style pea-flour cake",
    "老薑雞湯": "Old-ginger chicken soup",
    "老醋烧肉": "Aged-vinegar pork",
    "老醋花生": "Aged-vinegar peanuts",
    "老飯骨年菜": "LaoFanGu New Year dishes",
    "老饭骨祝全球的美食爱好者新年快乐！": "LaoFanGu New Year greetings",
    "肉包子": "Pork baozi",
    "肉夾饃": "Roujiamo",
    "肉粒扒茄子": "Braised eggplant with pork cubes",
    "肉餅": "Meat pie",
    "肥腸燉豆腐": "Intestine and tofu stew",
    "肥腸雞": "Intestine chicken",
    "胎菊綠豆爽": "Fetal-chrysanthemum mung-bean cooler",
    "胡桃豆腐": "Walnut tofu",
    "胡辣湯": "Hulatang",
    "脆炸時蔬": "Crispy fried seasonal vegetables",
    "脆爽腰花": "Crisp kidney flowers",
    "脆皮炸生蠔": "Crispy fried oysters",
    "脆皮炸酸奶": "Crispy fried yogurt",
    "脆皮爐鴨卷": "Crispy roast-duck rolls",
    "脆皮素燴": "Crispy-skin vegetable stew",
    "脆皮蝦卷": "Crispy shrimp rolls",
    "脆香餅": "Crisp fragrant cakes",
    "腐乳山药": "Fermented-tofu yam",
    "腐乳肉": "Fermented-tofu pork",
    "膠東熏雞": "Jiaodong smoked chicken",
    "臊子海參": "Minced-pork sea cucumber",
    "臘八粥": "Laba congee",
    "臘八蒜": "Laba garlic",
    "臘八蒜泡豬手": "Laba-garlic pig trotters",
    "臭鱖魚": "Stinky mandarin fish",
    "艾窩窩": "Ai wowuo",
    "芋頭扣肉": "Taro pork belly",
    "芋頭煲": "Taro claypot",
    "芒奶蝦": "Mango-milk shrimp",
    "芒果黑椒牛肉粒": "Mango black-pepper beef cubes",
    "芙蓉雞片": "Fu rong chicken slices",
    "芝麻豌豆蓉": "Sesame pea mash",
    "芥末蝦球": "Wasabi shrimp balls",
    "芫爆散丹": "Coriander-fried tripe",
    "花生奶酪": "Peanut cheese",
    "花生酪": "Peanut curd",
    "花雕雞": "Huadiao chicken",
    "芹皇鮮鮑絲": "Celery emperor fresh abalone shreds",
    "芽菜汆鮮魚": "Sprout dropped fresh fish",
    "苦瓜排骨湯": "Bitter-melon spare-rib soup",
    "苦瓜攤雞蛋": "Bitter melon with scrambled egg",
    "苦瓜芙蓉蛋": "Bitter-melon fu rong egg",
    "茄子大戰": "Eggplant showdown",
    "茄子拌面": "Eggplant mixed noodles",
    "茄子汆兒麵&西瓜露": "Dropped-eggplant noodles & watermelon dew",
    "茄汁乾燒大明蝦": "Tomato dry-braised king prawns",
    "茄汁牛肉": "Tomato-sauce beef",
    "茄汆面": "Dropped-eggplant noodles",
    "茯苓栗子羹": "Poria chestnut soup",
    "茯苓糕": "Poria cake",
    "草原雙魚": "Grassland two fish",
    "草菇炸雞": "Straw-mushroom fried chicken",
    "荊州炒雞拌面": "Jingzhou stir-fried chicken mixed noodles",
    "荔枝蝦圓": "Lychee shrimp balls",
    "荷包鯽魚": "Purse crucian carp",
    "荷花酥": "Lotus pastry",
    "荷葉鴨": "Lotus-leaf duck",
    "荷香牛扒": "Lotus-scented steak",
    "菊花酥": "Chrysanthemum pastry",
    "菜團子": "Vegetable buns",
    "菜片牛肉粒": "Vegetable-sliced beef cubes",
    "菜膽扒鮮鮑": "Choi sum with fresh abalone",
    "菠萝咕咾肉": "Pineapple sweet-and-sour pork",
    "菠蘿雞柳": "Pineapple chicken strips",
    "菠餃啤酒鴨": "Spinach-dumpling beer duck",
    "菲律賓可樂雞翅": "Filipino cola chicken wings",
    "萌叔炸醬": "Uncle Meng's fried sauce",
    "萝卜丝饼": "Shredded-radish cakes",
    "葱烧木耳": "Scallion-braised wood ear",
    "葱烧海参": "Scallion-braised sea cucumber",
    "葱爆羊肉": "Scallion-fried lamb",
    "蒜泥拌雞蛋": "Garlic mashed egg salad",
    "蒜燒雞翅煲": "Garlic chicken-wing pot",
    "蒜燜羊肉": "Garlic-smothered lamb",
    "蒜蓉豉汁蒸排骨": "Steamed ribs with garlic black bean",
    "蒜香小龍蝦": "Garlic crayfish",
    "蒜香排骨": "Garlic spare ribs",
    "蒜香豬蹄": "Garlic pig trotters",
    "蒜香麵包": "Garlic bread",
    "蒸带鱼": "Steamed hairtail",
    "蒸肉餅": "Steamed meat cake",
    "蒸酥雞": "Steamed crispy chicken",
    "蒸鸡翅": "Steamed chicken wings",
    "蓴菜魚圓湯": "Water-shield fish-ball soup",
    "蔓越莓": "Cranberry",
    "蔥油拌面": "Scallion-oil noodles",
    "蔥油肉丁炸醬": "Scallion-oil diced-pork zhajiang",
    "蔥油餅": "Scallion-oil pancakes",
    "蔥燒海參": "Scallion-braised sea cucumber",
    "蔥燒蹄筋": "Scallion-braised tendon",
    "蔥爆羊肉": "Scallion-fried lamb",
    "蔥花餅": "Scallion pancakes",
    "蔥辣小排": "Scallion-chili spare ribs",
    "蔬菜汁炖豆腐": "Vegetable-juice tofu stew",
    "薑母鴨": "Ginger-mother duck",
    "薑汁肘子": "Ginger-juice pork hock",
    "薑汁魚片": "Ginger-juice fish slices",
    "薺菜餃子": "Shepherd's-purse dumplings",
    "藍莓山藥": "Blueberry yam",
    "藕帶橋頭": "Lotus-stem bridge",
    "蘇州醬鴨": "Suzhou sauced duck",
    "蘇式月餅": "Suzhou-style mooncakes",
    "蘋果派": "Apple pie",
    "蘋果燴豬排": "Apple pork chops",
    "蘑菇丸子": "Mushroom meatballs",
    "蘸水羊肉": "Dipping-sauce lamb",
    "蘸汁牛肋": "Dipping-sauce beef ribs",
    "蘿蔔燉粉條": "Radish stewed glass noodles",
    "蘿蔔燉羊排": "Radish lamb-chop stew",
    "蘿蔔燉羊肉": "Radish lamb stew",
    "蘿蔔牛腩煲": "Radish beef-brisket pot",
    "虎皮尖椒": "Tiger-skin green chilies",
    "虎皮鳳爪": "Tiger-skin chicken feet",
    "虾爆鳝": "Shrimp-fried eel",
    "蚂蚁上树": "Ants climbing a tree",
    "蜜棗酥": "Honey-date pastry",
    "蜜汁火方": "Honey ham",
    "蜜汁肘子": "Honey pork hock",
    "蝦仁清湯麵": "Shrimp clear-broth noodles",
    "蝦仁餃子": "Shrimp dumplings",
    "蝦湯包燒黃漿": "Shrimp-soup tofu-skin rolls",
    "蝦皮炒冬瓜": "Dried-shrimp winter melon",
    "蝦頭燒豆腐": "Shrimp-head braised tofu",
    "蝦餃": "Har gow",
    "螃蟹3吃": "Crab three ways",
    "蟹粉小籠湯包": "Crab-roe xiaolongbao",
    "蟹粉拌油條": "Crab roe on youtiao",
    "蟹粉獅子頭": "Crab-roe lion's-head meatballs",
    "蟹黃大湯包": "Crab-roe soup dumplings",
    "蟹黃黄鱼羹": "Crab-roe yellow-croaker soup",
    "蠔油牛肉": "Oyster-sauce beef",
    "裹燒豆腐": "Wrapped braised tofu",
    "西湖醋魚": "West Lake vinegar fish",
    "西班牙海鮮飯": "Paella",
    "西瓜酪": "Watermelon junket",
    "西瓜雞": "Watermelon chicken",
    "西紅柿炒茄絲": "Tomato with shredded eggplant",
    "西紅柿炒雞蛋": "Tomato and egg",
    "西红柿炒蛋": "Tomato and egg",
    "西芹百合炒蝦仁": "Celery, lily bulb, and shrimp",
    "話梅小番茄": "Preserved-plum cherry tomatoes",
    "豆椒排骨": "Douban chili spare ribs",
    "豆椒肉絲": "Douban chili shredded pork",
    "豆瓣牛肉": "Douban beef",
    "豆瓣魚": "Douban fish",
    "豆腐腦": "Tofu pudding (doufunao)",
    "豆豉辣椒炒肉末": "Douchi chili minced pork",
    "豆豉辣椒炒臘肉": "Douchi chili Chinese bacon",
    "豉椒雞丁": "Black-bean chili diced chicken",
    "豉油皇炒麵": "Supreme soy sauce fried noodles",
    "豌豆燉雞": "Pea chicken stew",
    "豌豆糕": "Pea cake",
    "豌豆黄": "Pea-flour cake",
    "豐收棒子魚": "Harvest saury",
    "豚角煮": "Kakuni (Japanese braised pork)",
    "象形小辣椒": "Shaped mini chilies",
    "象眼鴿蛋": "Elephant-eye pigeon eggs",
    "豬耳凍": "Pig-ear aspic",
    "豬肉燉粉條": "Pork stewed glass noodles",
    "豬腳麵": "Pig-trotter noodles",
    "豬雜粥": "Pork-offal congee",
    "貴妃雞": "Imperial concubine chicken",
    "賽螃蟹": "Mock crab",
    "賽雞樅菌": "Mock chicken-fir mushrooms",
    "軟炸里脊": "Soft-fried tenderloin",
    "軟炸魚條": "Soft-fried fish strips",
    "辣味三汁燜鍋": "Spicy three-sauce claypot",
    "辣子里脊": "Chili tenderloin",
    "辣子雞": "Chongqing chili chicken",
    "辣子鸡": "Chongqing chili chicken",
    "辣椒炒肉": "Chili stir-fried pork",
    "辣滷鴨翅": "Spicy braised duck wings",
    "辣炒花蛤": "Spicy stir-fried clams",
    "辣醬螃蟹": "Chili-sauce crab",
    "迷迭香合味小龍蝦": "Rosemary crayfish",
    "迷迭香烤雞": "Rosemary roast chicken",
    "迷迭香熏大肠": "Rosemary smoked intestine",
    "連鍋湯": "Lian-guo soup",
    "過年醬點啥": "What to sauce for New Year",
    "過油肉": "Oil-passed pork",
    "避風塘炒大蝦": "Typhoon-shelter prawns",
    "避风塘炒蟹": "Typhoon-shelter crab",
    "酥炸大蝦": "Crispy fried prawns",
    "酥炸鳳尾蝦": "Crispy phoenix-tail prawns",
    "酥鯽魚": "Crispy crucian carp",
    "酥黃菜": "Crispy yellow eggs",
    "酱汁扒鸡": "Sauce-braised chicken",
    "酱牛肉": "Sauced beef",
    "酸奶饅頭": "Yogurt steamed buns",
    "酸汤馄饨": "Sour-broth wontons",
    "酸湯魚": "Sour-soup fish",
    "酸菜白肉": "Pickled cabbage with pork",
    "酸菜魚": "Pickled-cabbage fish",
    "酸蘿蔔鴨血粉絲湯": "Sour-radish duck-blood noodle soup",
    "酸辣湯": "Hot-and-sour soup",
    "酸辣湯&臘八蒜": "Hot-and-sour soup & laba garlic",
    "醋椒猪肝": "Vinegar-pepper pork liver",
    "醋溜咯吱": "Vinegar-fried gezhi",
    "醋溜白菜": "Vinegar-fried cabbage",
    "醋溜肉丝": "Vinegar-fried shredded pork",
    "醋溜苜蓿": "Vinegar-fried alfalfa sprouts",
    "醋熘白菜": "Vinegar-fried cabbage",
    "醪糟干烧鱼": "Fermented-rice dry-braised fish",
    "醬汁魚": "Sauced fish",
    "醬油汆面": "Soy dropped noodles",
    "醬燒牛肉": "Sauce-braised beef",
    "醬燒牛肋": "Sauce-braised beef ribs",
    "醬燜扁豆": "Sauce-smothered beans",
    "醬爆肉丁": "Sauce-fried diced pork",
    "醬爆雞丁": "Sauce-fried diced chicken",
    "醬牛肉": "Sauced beef",
    "醬肉": "Sauced pork",
    "醬肉包": "Sauced-pork bao",
    "醬肉餡餅": "Sauced-pork pies",
    "醬蟹": "Sauced crab",
    "醬豬蹄": "Sauced pig trotters",
    "醬雞": "Sauced chicken",
    "醬香爆炒雞": "Sauce-fragrant flash-fried chicken",
    "醬香餅": "Sauce-fragrant pancakes",
    "醬香鹹菜絲": "Sauce-fragrant pickled shreds",
    "醬鴿": "Sauced pigeon",
    "釀苦瓜": "Stuffed bitter melon",
    "重慶小面": "Chongqing small noodles",
    "金剛火方": "Jingang ham",
    "金桔文火肉排": "Kumquat slow-fire pork chops",
    "金桔牛肋": "Kumquat beef ribs",
    "金桔紅燒肉": "Kumquat red-braised pork",
    "金沙玉米": "Golden-sand corn",
    "金沙雞丁": "Golden-sand diced chicken",
    "金湯佛跳墻": "Golden-soup Buddha jumps over the wall",
    "金牌醋肘": "Gold-medal vinegar hock",
    "金米肥牛": "Golden-rice fatty beef",
    "金芽菜豆腐煲": "Golden-sprout tofu pot",
    "金蒜煎烹牛柳粒": "Golden-garlic pan-tossed beef cubes",
    "金銀干貝湯": "Gold-and-silver scallop soup",
    "金针菇茄子煲": "Enoki eggplant pot",
    "鉢鉢魚": "Bowl-bowl fish",
    "銀耳汽鍋雞": "White-fungus steam-pot chicken",
    "銀芽里脊絲": "Bean-sprout shredded tenderloin",
    "銀針粉": "Silver-needle noodles",
    "錢兔似錦": "Prosperous rabbit year",
    "鍋包大蝦": "Guo bao prawns",
    "鍋包肉": "Guo bao rou",
    "鍋塌羊肉": "Pan-collapsed lamb",
    "鍋塌豆腐": "Pan-collapsed tofu",
    "鍋塌里脊": "Pan-collapsed tenderloin",
    "鍋塌魚片": "Pan-collapsed fish slices",
    "鍋巴肉片": "Sizzling rice-crust pork",
    "鏡箱豆腐": "Mirror-box tofu",
    "鐵鍋燉大鵝": "Iron-pot stewed goose",
    "鐺爆肉": "Wok-flash pork",
    "長龍粽": "Long-dragon zongzi",
    "門釘肉餅": "Door-nail meat pies",
    "開水白菜": "Boiled-water cabbage",
    "陳皮胡鴨湯": "Tangerine-peel Hu duck soup",
    "陽春面": "Yangchun noodles",
    "陽春麵": "Yangchun noodles",
    "隆江豬腳飯": "Longjiang pig-trotter rice",
    "雞汁蘋果絲瓜": "Chicken-juice apple luffa",
    "雞油燒豆腐": "Chicken-fat braised tofu",
    "雞絲涼麵": "Shredded-chicken cold noodles",
    "雞肉粽子": "Chicken zongzi",
    "雞蓉銀耳": "Chicken-cream white fungus",
    "雞蛋炸醬": "Egg zhajiang",
    "雞裡蹦": "Ji li beng",
    "雞豆花": "Chicken tofu pudding",
    "雪碧雞翅": "Sprite chicken wings",
    "雪花桃泥": "Snowflake peach mash",
    "雪花澳帶": "Snowflake scallops",
    "雷公根甘蔗汁": "Gotu kola sugarcane juice",
    "霸王滷肉飯": "Overlord lu rou fan",
    "青椒肉花": "Green-pepper pork flowers",
    "青芥羅氏蝦": "Wasabi giant freshwater prawns",
    "青菜豆腐丸子": "Greens and tofu balls",
    "面果大棗": "Fried dough with jujube",
    "面果核桃": "Fried dough with walnut",
    "面果白菜": "Fried dough with cabbage",
    "韭菜盒子": "Chive pockets",
    "韭菜蝦皮卷煎餅": "Chive dried-shrimp jianbing",
    "韭黃肉絲煎面": "Yellow-chive shredded-pork pan-fried noodles",
    "預告": "Preview",
    "養生羊排": "Tonic lamb chops",
    "養生肥牛": "Tonic fatty beef",
    "饞醬": "Crave-sauce",
    "香果雞": "Fragrant-fruit chicken",
    "香椿涼麵": "Toon cold noodles",
    "香椿牛肉": "Toon beef",
    "香椿絨魚條": "Toon velvet fish strips",
    "香椿臭餡餅": "Toon stinky pies",
    "香椿魚": "Toon fish",
    "香橙沙律蝦": "Orange salad shrimp",
    "香橙荔枝蝦球": "Orange lychee shrimp balls",
    "香芋豉汁蒸滑雞": "Taro black-bean steamed chicken",
    "香菇瓤菜心": "Shiitake stuffed greens",
    "香菇雞絲": "Shiitake shredded chicken",
    "香蔥油淋魚": "Scallion-oil fish",
    "香辣土豆絲": "Spicy shredded potato",
    "香辣排骨": "Spicy spare ribs",
    "香辣豬蹄": "Spicy pig trotters",
    "香辣金錢蛋": "Spicy coin eggs",
    "香辣鱼头泡饭": "Spicy fish-head over rice",
    "香酥牛肉": "Crispy fragrant beef",
    "香酥羊排": "Crispy fragrant lamb chops",
    "香酥雞": "Crispy fragrant chicken",
    "香酥雞腿": "Crispy fragrant drumsticks",
    "香酥鴨": "Crispy fragrant duck",
    "驢打滾": "Donkey rolls (yellow-soybean pastry)",
    "髮絲百葉": "Hair-thin tripe",
    "魚香肉絲": "Yu-xiang shredded pork",
    "魚香茄子": "Yu-xiang eggplant",
    "魚香蒸蛋": "Yu-xiang steamed egg",
    "魚香雞扒": "Yu-xiang chicken steak",
    "魚香鴨方": "Yu-xiang duck squares",
    "鮁魚餃子": "Mackerel dumplings",
    "鮑汁佛跳牆": "Abalone-sauce Buddha jumps over the wall",
    "鮑魚三鮮": "Abalone three delicacies",
    "鮑魚紅燒肉": "Abalone red-braised pork",
    "鮑魚茄盒": "Abalone eggplant sandwiches",
    "鮑魚雞翅": "Abalone chicken wings",
    "鮮筍蒸滑雞": "Fresh-bamboo steamed silky chicken",
    "鮮蝦奶油意面": "Creamy shrimp pasta",
    "鮮蝦春筍獅子頭": "Shrimp spring-bamboo lion's-head meatballs",
    "鮮豌豆燴鱸魚": "Fresh-pea sea bass",
    "鮮豌豆粉蒸魚丁": "Fresh-pea rice-flour steamed fish cubes",
    "鯽魚湯": "Crucian carp soup",
    "鱔魚兩吃": "Eel two ways",
    "鱖魚獅子頭": "Mandarin-fish lion's-head meatballs",
    "鱸魚獅子頭": "Sea-bass lion's-head meatballs",
    "鱼香脆皮虾": "Yu-xiang crispy shrimp",
    "鲜虾鸡煲": "Fresh-shrimp chicken pot",
    "鳳尾蝦啫粉絲": "Phoenix-tail prawns with sizzling glass noodles",
    "鸡豆花": "Chicken tofu pudding",
    "鹽水遲菜心": "Salt-water delayed choi sum",
    "鹽滷肚": "Salt-brine tripe",
    "鹽焗排骨": "Salt-baked spare ribs",
    "鹽焗鮑魚": "Salt-baked abalone",
    "鹽煎肉": "Salt-fried pork",
    "鹽燒風味雞柳": "Salt-grilled chicken strips",
    "麒麟魚": "Qilin fish",
    "麵包蝦排": "Breaded shrimp cutlets",
    "麻婆豆腐": "Mapo tofu",
    "麻豆腐": "Ma doufu",
    "麻辣仔雞": "Mala young chicken",
    "麻辣脫骨雞": "Mala boneless chicken",
    "麻醬涼麵": "Sesame-sauce cold noodles",
    "麻醬燒餅": "Sesame-sauce shaobing",
    "麻醬糖餅": "Sesame-sauce sweet cakes",
    "麻香雞排": "Sesame chicken cutlet",
    "黃燜乳鴿": "Yellow-braised squab",
    "黃燜羊肉": "Yellow-braised lamb",
    "黃燜雞": "Yellow-braised chicken",
    "黃瓜三吃": "Cucumber three ways",
    "黃瓜熘里脊片": "Cucumber sauced tenderloin",
    "黃豆燜豬蹄": "Soybean pig trotters",
    "黃金炒飯": "Golden fried rice",
    "黄金白菜卷": "Golden cabbage rolls",
    "黑咖牛肉餃子": "Black-coffee beef dumplings",
    "黑椒炒麵": "Black-pepper fried noodles",
    "黑椒牛柳粒": "Black-pepper beef cubes",
    "黑椒雞錘": "Black-pepper chicken drums",
    "黑椒香橙雞翅": "Black-pepper orange chicken wings",
    "黑醋带鱼卷": "Black-vinegar hairtail rolls",
    "黑麻醬糖花卷": "Black-sesame sweet flower rolls",
    "乾燴大蝦": "Dry-braised prawns",
}

DISH["乾燴大蝦"] = "Dry-braised prawns"  # U+3E06 in the YouTube title
DISH["\u4e7e\u3e06\u5927\u8766"] = "Dry-braised prawns"

UNPARSED = {
    "炒菜中途要加水嗎？凍肉怎麼處理？14個答疑解惑小技巧，總有一個是你需要的！": "Should you add water mid-stir-fry? How to handle frozen meat? 14 Q&As",
    "馬志和老師的師門傳承分享會，祝大家新春策馬，一路繁花！": "Chef Ma Zhihe's lineage sharing session — New Year greetings",
    "所有的小飯骨們，新年快樂，闔家辛福！": "Happy New Year to all the little FanGu",
    "年夜飯十萬個怎麼辦？壓軸菜涼了咋加熱？魚蒸老了怎麼救？硬核解答來了！": "New Year's Eve emergencies: reheating the finale, rescuing over-steamed fish",
    "和社區鄰居們一起包餃子啦！祝大家新年快樂，五福臨門！": "Making dumplings with the neighbors — Happy New Year",
    "直擊小廚娘後廚！軟糯入味的紅燒肉，酥香酸甜的松鼠桂魚，口水根本止不住～": "In the little cook's kitchen: red-braised pork and squirrel fish",
    "無語哥 (Khaby Lame) 和埃文凱爾 (Evan Kail) 來淮四九宴吃烤鴨啦，一口吃出幾個表情包": "Khaby Lame and Evan Kail eat roast duck at Huai Si Jiu Yan",
    "油燜大蝦對決！2位廚師的較量，翻車還是險勝？做飯原來這麼刺激～": "Oil-braised prawn showdown: two chefs compete",
    "里脊三炸•總結篇！顏色不同烹調不同，味道口感也不同，你最喜歡那個？": "Tenderloin three fryings — recap: color, method, and texture",
    "新年新氣象，我們搬家啦！老飯骨全體給大家拜年啦，過年好~": "We moved house — LaoFanGu New Year greetings",
    "耗時兩天！用十幾種食材復刻90年代“國風彩鳳”！2025祝大家吉祥如意，福氣滿滿～": "Two days and a dozen ingredients: recreating 1990s 'national-style colorful phoenix'",
    "挑戰做300份公益愛心餐，全程耗時三天！但他們卻默默堅持了8年…": "300 charity meals in three days — they've done this quietly for eight years",
    "我想說：我會好好吃飯，讓身體健健康康！祖國媽媽，祝您生日快樂！": "I'll eat well and stay healthy — happy birthday, motherland",
    "國宴大師線下開課啦！不僅有傳承還有創新，《總廚的絕味》第一季比賽太精彩~": "Masters teaching offline: season 1 of The Executive Chef's Secret Flavors",
    "請國宴大師還原《中華小當家》彈跳甲魚湯！把湯做成玻璃球你敢信嗎？": "Recreating Cooking Master Boy's bouncing turtle soup",
    "正陽門外宴江南，老飯骨淮四九宴開業啦！來了可不止為了賞味……": "Huai Si Jiu Yan opens outside Zhengyangmen",
    "到「中國農業大學」給學生“開小竈”！真的只是好吃億點點~": "A small stove for students at China Agricultural University",
    "今天是2月1日，老飯骨5歲了！ 七尺灶台，五載陪伴，感恩小飯骨~": "LaoFanGu turns 5 — five years at the stove",
    "和老飯骨大師一起聊聊天！回憶那些年學徒的日子": "Chat with the masters: apprentice years",
    "老飯骨聊廚師理論知識！沉下心學好基本功，才能給廚藝注入靈魂~": "Kitchen theory: fundamentals before soul",
    "老飯骨淮揚菜博物館遊記！深厚的底蘊，說不盡的故事和感慨": "Visit to the Huaiyang cuisine museum",
    "老飯骨是怎樣煉成的？回憶二伯師父庹代良": "How LaoFanGu was forged: remembering Er Bo's teacher Tuo Dailiang",
    "馬老師的師門會！6個徒弟做6個菜繫的清真菜！青出於藍而勝於藍，真正解讀守正創新": "Chef Ma's lineage gathering: six disciples, six halal cuisines",
    "老飯骨草原之行VLOG！走出廚房，面向群眾，讓廚藝之道展翅高飛！": "LaoFanGu grassland vlog",
    "老飯骨進校園！客廚中國人民大學！學生們從二樓排到一樓門口，太熱情了~": "Guest cooking at Renmin University",
    "一年了，大家都很想您！我們也有好好吃飯，願您在那裡有戲聽，有茶喝，不再操心，多多享福！": "One year on: remembering Grandpa Zheng — we are eating well",
    "老飯骨拜年啦！祝小飯骨們兔年大吉，萬事勝意，錢兔似錦！": "LaoFanGu New Year: year of the rabbit",
    "和李立宏老師 共同為小饭骨们端上一盤熱氣騰騰的餃子！感謝李老師好吃的聲音！": "Dumplings with narrator Li Lihong",
    "小飯骨們，記得好好吃飯呦！": "Little FanGu: remember to eat well",
    "大爷，一路走好": "Grandpa Zheng, rest well",
    "跨界聯動！奧運冠軍楊倩跟大爺二伯一起做油燜大蝦！": "Olympic champion Yang Qian cooks oil-braised prawns with Grandpa and Er Bo",
    "國宴大師教你做家常菜，歡迎大家訂閱老飯骨！Thank you for subscribing to our channel.": "State banquet masters cook home food — thanks for subscribing",
}

LABEL = {
    "public_chinese_only": "Public · Chinese only",
    "public_english": "Public · English captions on YouTube",
    "member_only": "Members only",
}


def cjk_count(s: str) -> int:
    return sum(1 for ch in s if "\u4e00" <= ch <= "\u9fff")


def translate_title(zh: str) -> str:
    raw = zh.strip()
    raw = re.sub(r"\s*[|｜]\s*老[飯饭]骨\s*$", "", raw)
    key = re.sub(r"[～~\s]+$", "", raw)
    if key in UNPARSED:
        return UNPARSED[key]
    # loose match unparsed
    for k, v in UNPARSED.items():
        if raw.startswith(k[:12]):
            return v

    m = re.match(r"【([^】•]+)•([^】]+)】(.*)", raw)
    if m:
        prefix, dish, tag = m.group(1).strip(), m.group(2).strip(), m.group(3).strip(" ～~")
        pre = PREFIX.get(prefix, prefix)
        d = DISH.get(dish) or DISH.get(dish.replace("麵", "面")) or dish
        tag = re.sub(r"\s*[|｜]\s*老[飯饭]骨\s*$", "", tag).strip(" ～~")
        if tag and cjk_count(tag) < 4:
            return f"{pre} · {d} — {tag}" if tag else f"{pre} · {d}"
        return f"{pre} · {d}"
    m = re.match(r"【([^】]+)】(.*)", raw)
    if m:
        dish = m.group(1).strip()
        d = DISH.get(dish, dish)
        return d
    if cjk_count(raw) == 0:
        return raw
    return raw


def main() -> None:
    src = ROOT / "catalog.csv"
    rows = list(csv.DictReader(src.open(encoding="utf-8")))
    missing = []
    for r in rows:
        t = r["title"]
        m = re.match(r"【([^】•]+)•([^】]+)】", t)
        if m:
            dish = m.group(2).strip()
            if dish not in DISH and dish.replace("麵", "面") not in DISH:
                missing.append(dish)
    if missing:
        uniq = sorted(set(missing))
        print("MISSING DISHES", len(uniq))
        for d in uniq:
            print(" ", d)

    out_rows = []
    for r in rows:
        en = translate_title(r["title"])
        out_rows.append({**r, "title_en": en, "title_zh": r["title"]})

    csv_path = ROOT / "catalog-en.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=["category", "date", "duration", "id", "title_en", "title_zh", "subtitles", "url"],
        )
        w.writeheader()
        for r in out_rows:
            w.writerow({k: r[k] for k in w.fieldnames})

    n = {c: sum(1 for r in out_rows if r["category"] == c) for c in LABEL}
    md = []
    md.append("# LaoFanGu video catalog (English titles)")
    md.append("")
    md.append("Channel: [LaoFanGu / 老饭骨](https://www.youtube.com/@LaoFanGu)")
    md.append(f"Same {len(out_rows)} videos as [catalog.md](catalog.md), with English titles.")
    md.append("")
    md.append("| Category | Count |")
    md.append("| --- | ---: |")
    md.append(f"| Public, Chinese only (no English subs/dub on YouTube) | {n['public_chinese_only']} |")
    md.append(f"| Public, with English captions on YouTube | {n['public_english']} |")
    md.append(f"| Members only | {n['member_only']} |")
    md.append("")
    md.append("Dish names are translated; series labels: **State Banquet Master**, **LaoFanGu Classroom**, etc. Original Chinese is in [catalog.md](catalog.md) and the `title_zh` column of [catalog-en.csv](catalog-en.csv).")
    md.append("")
    md.append("For the English-subtitle pipeline, process **public_chinese_only** and skip the other two.")
    md.append("")
    for cat, label in LABEL.items():
        chunk = [r for r in out_rows if r["category"] == cat]
        md.append(f"## {label} ({len(chunk)})")
        md.append("")
        md.append("| Date | Length | Title | URL |")
        md.append("| --- | --- | --- | --- |")
        for r in chunk:
            title = r["title_en"].replace("|", "\\|")
            extra = ""
            if cat == "public_english" and r.get("subtitles"):
                extra = f" · YouTube subs: {r['subtitles']}"
            md.append(f"| {r['date']} | {r['duration']} | {title}{extra} | [{r['id']}]({r['url']}) |")
        md.append("")
    (ROOT / "catalog-en.md").write_text("\n".join(md), encoding="utf-8")
    still_cjk = sum(1 for r in out_rows if cjk_count(r["title_en"]) >= 4)
    print("wrote", csv_path.name, (ROOT / "catalog-en.md").name)
    print("titles still mostly Chinese", still_cjk)
    print("missing dishes", len(set(missing)))


if __name__ == "__main__":
    main()
